### ISSUE TITLE
스케치북 사진 파일과 겹침 문제

### ISSUE THREAD

**Issue by 425range** [anseonghwan/KW_Open-Source_Project_team08#16]
스케치북 이미지를 업로드하면 뒤에 전 사람이 그린 그림이 나오게 되는데
사람이 그린 그림을 스케치북 이미지가 가리는 상태임.

-> 스케치북 이미지를 삭제하거나 뒤에 까는 방법 필요

**Comment by anseonghwan** [comment]
Pull requests #20
